### ISSUE TITLE
Could you provide the version of each package?

### ISSUE THREAD

**Issue by wchstorm1** [eric-mitchell/detect-gpt#3]
I installed python3.8, but it doesn't work correctly. Thank you.

**Comment by eric-mitchell** [comment]
I attached the output of `pip freeze` for my Python 3.8.10 env, though keep in mind that this list probably contains a lot of unnecessary libraries I installed at various points during development. Can you provide more specific info beyond the code not working?

[freeze.txt](https://github.com/eric-mitchell/detect-gpt/files/10876888/freeze.txt)

**Comment by eric-mitchell** [comment]
Closing this but feel free to re-open if you're still having issues.
