### ISSUE TITLE
Getting Permission denied error

### ISSUE THREAD

**Issue by svk-cu-nlp** [eric-mitchell/detect-gpt#5]
**I am trying to execute the following command** 
python run.py --output_name n_perturb --base_model_name gpt2-medium --mask_filling_model_name t5-small --n_perturbation_list 1,10,100,1000 --n_samples 100 --pct_words_masked 0.3 --span_length 2

**Getting the following error:**
with open(file_path, encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\SOUVIK\\.cache\\huggingface\\datasets\\downloads\\extracted\\6c23c0182c80c071cd57f17c1b534be8fa7ea6cb31f30c8dd7a95bf1ed1b0d33.py'

**Comment by eric-mitchell** [comment]
This might be an issue with your NFS if you’re using a networked filesystem that you periodically need to login to. You could also try deleting your transformers cache and re-running. Alternatively, manually set the cache_dir= when loading models/datasets from huggingface to a different directory.



From: SVK_CU_NLP ***@***.***>
Date: Saturday, April 29, 2023 at 9:56 AM
To: eric-mitchell/detect-gpt ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [eric-mitchell/detect-gpt] Getting Permission denied error (Issue #5)

I am trying to execute the following command
python run.py --output_name n_perturb --base_model_name gpt2-medium --mask_filling_model_name t5-small --n_perturbation_list 1,10,100,1000 --n_samples 100 --pct_words_masked 0.3 --span_length 2

Getting the following error:
with open(file_path, encoding="utf-8") as f:
PermissionError: [Errno 13] Permission denied: 'C:\Users\SOUVIK\.cache\huggingface\datasets\downloads\extracted\6c23c0182c80c071cd57f17c1b534be8fa7ea6cb31f30c8dd7a95bf1ed1b0d33.py'

**Comment by eric-mitchell** [comment]
Closing this issue, but feel free to re-open if you're still having any issues!
